function [traj, t_sample] = gen_traj()

T = 10;
fs = 1000;
waypoints = [ ...
    0, 0, 0; ...
    0, 2, 0; ...
    2, 2, 0; ...
    2, 0, 0; ...
    0, 0, 0; ...
];
AutoPitch = false;
AutoBank = false;

waypoint_ts = linspace(0, T, size(waypoints, 1)).';
traj = waypointTrajectory(waypoints, waypoint_ts, ...
    AutoPitch = AutoPitch, ...
    AutoBank = AutoBank ...
);

t_sample = [0 : 1/fs : T-1/fs].';

end
